-- 코드를 입력하세요
SELECT FP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS M
ON FP.CATEGORY = M.CATEGORY AND FP.PRICE = M.MAX_PRICE
WHERE FP.CATEGORY = '과자' OR FP.CATEGORY = '국' OR FP.CATEGORY = '김치' OR FP.CATEGORY = '식용유'
ORDER BY MAX_PRICE DESC;